Repository ONRR/doi-extractives-data, pull requests merged in 2018-06, with the labels that each got.

#2885 Add tabs to style guide
  _sass/components/_tabs.scss
  nrrd-design-system/components/components/tabs/README.md
  nrrd-design-system/components/components/tabs/tabs.config.yml
  nrrd-design-system/components/components/tabs/tabs.hbs
Labels: workflow:testing

#2919 Add subpage navigation component to style guide
  nrrd-design-system/components/components/navigation/side-navigation/README.md
  nrrd-design-system/components/components/navigation/side-navigation/side-navigation.config.yml
  nrrd-design-system/components/components/navigation/side-navigation/side-navigation.hbs
  nrrd-design-system/components/components/navigation/subpage-navigation/README.md
  nrrd-design-system/components/components/navigation/subpage-navigation/subpage-navigation.config.yml
  nrrd-design-system/components/components/navigation/subpage-navigation/subpage-navigation.hbs
Labels: workflow:testing

#2927 Adds book icon to includes
  _includes/svg/icon-book.svg
Labels: workflow:testing

#2924 Simplifying style guide structure and adding documentation
  nrrd-design-system/components/components/callout-cards/README.md
  nrrd-design-system/components/components/cards/README.md
  nrrd-design-system/components/components/cards/cards.config.yml
  nrrd-design-system/components/components/cards/cards.hbs
  nrrd-design-system/components/components/tables/advanced-table/advanced-table.config.yml
  nrrd-design-system/components/components/tables/advanced-table/advanced-table.hbs
  nrrd-design-system/components/components/tables/basic-table/basic-table.config.yml
  nrrd-design-system/components/components/tables/basic-table/basic-table.hbs
  nrrd-design-system/components/styles/colors/primary-palette/README.md
  nrrd-design-system/components/styles/colors/primary-palette/primary-palette.config.yml
  nrrd-design-system/components/styles/colors/primary-palette/primary-palette.hbs
  nrrd-design-system/components/styles/colors/supporting-palette/README.md
  nrrd-design-system/components/styles/colors/supporting-palette/supporting-palette.config.yml
  nrrd-design-system/components/styles/colors/supporting-palette/supporting-palette.hbs
  nrrd-design-system/components/styles/icons/README.md
  nrrd-design-system/components/styles/icons/icons.config.yml
  nrrd-design-system/components/styles/icons/icons.hbs
  nrrd-design-system/components/styles/typography/README.md
  nrrd-design-system/components/styles/typography/typography.config.yml
  nrrd-design-system/components/styles/typography/typography.hbs
  nrrd-design-system/components/typography/README.md
Labels: workflow:testing

#2948 Increments version to 3.1.8
  _config.yml
Labels: workflow:testing

#2949 dev-->staging
  _config.yml
  _how-it-works/audits-and-assurances.md
  _how-it-works/coal-excise-tax.md
  _how-it-works/corporate-income-tax.md
  _how-it-works/forestry.md
  _how-it-works/fossil-fuels.md
  _how-it-works/laws-and-regulations/federal-laws.md
  _how-it-works/laws-and-regulations/federal-reforms.md
  _how-it-works/laws-and-regulations/state-laws-and-regulations.md
  _how-it-works/lease-process-offshore.md
  _how-it-works/lease-process-onshore.md
  _how-it-works/natural-resources/ownership.md
  _how-it-works/natural-resources/revenues.md
  _how-it-works/nonenergy-minerals.md
  _how-it-works/renewables.md
  _how-it-works/tribal-economic-impact.md
  _how-it-works/tribal-ownership-and-governance.md
  _how-it-works/tribal-production.md
  _how-it-works/tribal-revenue.md
  _includes/offshore-area-map.html
  _includes/svg/icon-book.svg
  _sass/components/_tabs.scss
  nrrd-design-system/components/components/callout-cards/README.md
  nrrd-design-system/components/components/cards/README.md
  nrrd-design-system/components/components/cards/cards.config.yml
  nrrd-design-system/components/components/cards/cards.hbs
  nrrd-design-system/components/components/icons/README.md
  nrrd-design-system/components/components/navigation/side-navigation/README.md
  nrrd-design-system/components/components/navigation/side-navigation/side-navigation.config.yml
  nrrd-design-system/components/components/navigation/side-navigation/side-navigation.hbs
  nrrd-design-system/components/components/navigation/subpage-navigation/README.md
  nrrd-design-system/components/components/navigation/subpage-navigation/subpage-navigation.config.yml
  nrrd-design-system/components/components/navigation/subpage-navigation/subpage-navigation.hbs
  nrrd-design-system/components/components/tables/advanced-table/advanced-table.config.yml
  nrrd-design-system/components/components/tables/advanced-table/advanced-table.hbs
  nrrd-design-system/components/components/tables/basic-table/basic-table.config.yml
  nrrd-design-system/components/components/tables/basic-table/basic-table.hbs
  nrrd-design-system/components/components/tabs/README.md
  nrrd-design-system/components/components/tabs/tabs.config.yml
  nrrd-design-system/components/components/tabs/tabs.hbs
  nrrd-design-system/components/layouts/basic-text-page/basic-text-page.hbs
  nrrd-design-system/components/styles/colors/primary-palette/README.md
  nrrd-design-system/components/styles/colors/primary-palette/primary-palette.config.yml
  nrrd-design-system/components/styles/colors/primary-palette/primary-palette.hbs
  nrrd-design-system/components/styles/colors/supporting-palette/README.md
  nrrd-design-system/components/styles/colors/supporting-palette/supporting-palette.config.yml
  nrrd-design-system/components/styles/colors/supporting-palette/supporting-palette.hbs
  nrrd-design-system/components/styles/icons/README.md
  nrrd-design-system/components/styles/icons/icons.config.yml
  nrrd-design-system/components/styles/icons/icons.hbs
  nrrd-design-system/components/styles/typography/README.md
  nrrd-design-system/components/styles/typography/typography.config.yml
  nrrd-design-system/components/styles/typography/typography.hbs
  nrrd-design-system/components/typography/README.md
Labels: workflow:testing

#2951 Adds height attribute to SVG icons for IE display
  _includes/svg/icon-coal.svg
  _includes/svg/icon-data-docs.svg
  _includes/svg/icon-download-base.svg
  _includes/svg/icon-download.svg
  _includes/svg/icon-geothermal.svg
  _includes/svg/icon-hardrock.svg
  _includes/svg/icon-oil.svg
  _includes/svg/icon-renewables.svg
Labels: workflow:testing

#2953 Pulls in IE icon fixes to release.
  _includes/svg/icon-coal.svg
  _includes/svg/icon-data-docs.svg
  _includes/svg/icon-download-base.svg
  _includes/svg/icon-download.svg
  _includes/svg/icon-geothermal.svg
  _includes/svg/icon-hardrock.svg
  _includes/svg/icon-oil.svg
  _includes/svg/icon-renewables.svg
Labels: workflow:testing

#2955 Fix of Tribal link text
  _how-it-works/tribal-ownership-and-governance.md
Labels: workflow:testing

#2954 Adds FY Production Data
  _downloads/federal-production.md
  downloads/federal_production_FY2008-2017_2018-06-15.xlsx
Labels: workflow:testing

#2971 Clarifies timeframe for available production data in summary
  _downloads/default.md
Labels: workflow:testing

#2969 Dev-->Staging
  _config.yml
  _downloads/default.md
  _downloads/federal-production.md
  _how-it-works/tribal-ownership-and-governance.md
  downloads/federal_production_FY2008-2017_2018-06-15.xlsx
Labels: workflow:testing

#2972 Staging--> Master
  _config.yml
  _downloads/default.md
  _downloads/federal-production.md
  _how-it-works/tribal-ownership-and-governance.md
  downloads/federal_production_FY2008-2017_2018-06-15.xlsx
Labels: workflow:testing

#2941 initial gatsby add
  .dockerignore
  _config.yml
  gatsby-site/.eslintrc
  gatsby-site/.gitignore
  gatsby-site/.prettierrc
  gatsby-site/LICENSE
  gatsby-site/README.md
  gatsby-site/gatsby-browser.js
  gatsby-site/gatsby-config.js
  gatsby-site/gatsby-node.js
  gatsby-site/gatsby-ssr.js
  gatsby-site/package-lock.json
  gatsby-site/package.json
  gatsby-site/src/components/Drawer/index.js
  gatsby-site/src/components/Header/Hamburger.js
  gatsby-site/src/components/Header/index.js
  gatsby-site/src/layouts/index.js
  gatsby-site/src/pages/404.js
  gatsby-site/src/pages/index.js
  gatsby-site/src/pages/page-2.js
  gatsby-site/src/state/app.js
  gatsby-site/src/state/createStore.js
  gatsby-site/src/state/index.js
  gatsby-site/src/utils/theme.js
  gatsby-site/src/utils/typography.js
Labels: enhancement:tech, p2

#2936 Federal reform content updates
  _how-it-works/laws-and-regulations/federal-reforms.md
Labels: workflow:testing

#2998 Repairs broken links on federal laws and regs page
  _how-it-works/laws-and-regulations/federal-laws.md
Labels: workflow:testing

#2984 Changes repo path in preview plugin, site footer, and other instances
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  _downloads/default.md
  _downloads/disbursements.md
  _downloads/federal-production.md
  _downloads/federal-revenue-by-company.md
  _downloads/federal-revenue-by-location.md
  _includes/layout/footer.html
  _plugins/federalist-preview.rb
  _sass/blocks/_banner.scss
  data/README.md
  data/disbursements/README.md
  data/gdp/README.md
  data/revenue/README.md
  nrrd-design-system/components/components/global-footer/global-footer.hbs
  nrrd-design-system/components/components/hero-ribbons/hero-ribbons.hbs
  package.json
Labels: workflow:testing

#3003 fixed title tag closure
  _includes/case-studies/maps/AK.svg
  _includes/case-studies/maps/AZ-greenlee.svg
  _includes/case-studies/maps/AZ-pima.svg
  _includes/case-studies/maps/CA.svg
  _includes/case-studies/maps/LA.svg
  _includes/case-studies/maps/MI.svg
  _includes/case-studies/maps/MN.svg
  _includes/case-studies/maps/NV-elko-eureka.svg
  _includes/case-studies/maps/NV-humboldt-lander.svg
  _includes/case-studies/maps/TX.svg
  _includes/case-studies/maps/WV.svg
  _includes/case-studies/maps/WY.svg
  package-lock.json
  package.json
Labels: bug:content, workflow:testing

#2947 Expands GOMESA supporting content
  _data/terms.yml
  _how-it-works/laws-and-regulations/federal-laws.md
  _how-it-works/laws-and-regulations/gomesa.md
  downloads/gomesa-map.pdf
Labels: workflow:testing
