Repository ONRR/doi-extractives-data, pull requests merged in 2018-05, with the labels that each got.

#2811 Fixes link causing infinite redirect loop
  _how-it-works/default.md
Labels: workflow:testing

#2836 Dev-->Staging
  _config-dev.yml
  _config.yml
  _data/fund_names.yml
  _downloads/disbursements.md
  _how-it-works/coal-excise-tax.md
  _how-it-works/default.md
  _how-it-works/tribal-economic-impact.md
  _includes/location/national-disbursements.html
  js/components/bar-chart-table.js
Labels: workflow:testing

#2842 fixed withheld flag check
  _includes/location/display-federal-production-county.html
  js/components/bar-chart-table.js
  package.json
Labels: workflow:testing

#2844 Renames footer to global footer in style guide
  nrrd-design-system/components/components/footer/footer.config.yml
  nrrd-design-system/components/components/global-footer/README.md
  nrrd-design-system/components/components/global-footer/global-footer.config.yml
  nrrd-design-system/components/components/global-footer/global-footer.hbs
Labels: style guide, workflow:testing

#2845 2743 low chart values
  js/components/eiti-bar-chart.js
Labels: workflow:testing

#2843 docs: Move tables to top level
  _sass/components/_article-table.scss
  nrrd-design-system/components/layouts/tables/tables.hbs
  nrrd-design-system/components/tables/advanced-table/advanced-table.config.yml
  nrrd-design-system/components/tables/advanced-table/advanced-table.hbs
  nrrd-design-system/components/tables/basic-table/basic-table.config.yml
  nrrd-design-system/components/tables/basic-table/basic-table.hbs
Labels: workflow:testing

#2867 Added a 0 label if no royalties were collected
  _includes/location/revenue-type-row-oilgas.html
Labels: bug:content

#2871 Dev-->Staging
  _config.yml
  _includes/how-it-works/coal_involved.html
  _includes/how-it-works/minerals_involved.html
  _includes/how-it-works/offshore_oil_gas_involved.html
  _includes/how-it-works/offshore_renewables_involved.html
  _includes/how-it-works/onshore_oil_gas_involved.html
  _includes/how-it-works/onshore_renewables_involved.html
  _includes/location/display-federal-production-county.html
  _includes/location/revenue-type-row-oilgas.html
  _sass/components/_article-table.scss
  _sass/components/_eiti-bar-chart.scss
  _sass/components/_icons.scss
  _sass/components/_ribbon.scss
  _sass/print/_ribbon-card.scss
  img/icons/envelope.svg
  img/icons/facebook.svg
  img/icons/flickr.svg
  img/icons/info.svg
  img/icons/instagram.svg
  img/icons/pinterest.svg
  img/icons/tumblr.svg
  img/icons/twitter.svg
  img/icons/youtube-play.svg
  js/components/bar-chart-table.js
  js/components/eiti-bar-chart.js
  nrrd-design-system/components/components/breadcrumbs/README.md
  nrrd-design-system/components/components/breadcrumbs/breadcrumbs.config.yml
  nrrd-design-system/components/components/breadcrumbs/breadcrumbs.hbs
  nrrd-design-system/components/components/footer/footer.config.yml
  nrrd-design-system/components/components/global-footer/README.md
  nrrd-design-system/components/components/global-footer/global-footer.config.yml
  nrrd-design-system/components/components/global-footer/global-footer.hbs
  nrrd-design-system/components/components/hero-ribbons/hero-ribbons.hbs
  nrrd-design-system/components/layouts/tables/tables.hbs
  nrrd-design-system/components/tables/advanced-table/advanced-table.config.yml
  nrrd-design-system/components/tables/advanced-table/advanced-table.hbs
  nrrd-design-system/components/tables/basic-table/basic-table.config.yml
  nrrd-design-system/components/tables/basic-table/basic-table.hbs
  package.json
  pages/about.html
Labels: workflow:testing

#2875 Staging-->Master
  _config.yml
  _includes/how-it-works/coal_involved.html
  _includes/how-it-works/minerals_involved.html
  _includes/how-it-works/offshore_oil_gas_involved.html
  _includes/how-it-works/offshore_renewables_involved.html
  _includes/how-it-works/onshore_oil_gas_involved.html
  _includes/how-it-works/onshore_renewables_involved.html
  _includes/location/display-federal-production-county.html
  _includes/location/revenue-type-row-oilgas.html
  _sass/components/_article-table.scss
  _sass/components/_eiti-bar-chart.scss
  _sass/components/_icons.scss
  _sass/components/_ribbon.scss
  _sass/print/_ribbon-card.scss
  img/icons/envelope.svg
  img/icons/facebook.svg
  img/icons/flickr.svg
  img/icons/info.svg
  img/icons/instagram.svg
  img/icons/pinterest.svg
  img/icons/tumblr.svg
  img/icons/twitter.svg
  img/icons/youtube-play.svg
  js/components/bar-chart-table.js
  js/components/eiti-bar-chart.js
  nrrd-design-system/components/components/breadcrumbs/README.md
  nrrd-design-system/components/components/breadcrumbs/breadcrumbs.config.yml
  nrrd-design-system/components/components/breadcrumbs/breadcrumbs.hbs
  nrrd-design-system/components/components/footer/footer.config.yml
  nrrd-design-system/components/components/global-footer/README.md
  nrrd-design-system/components/components/global-footer/global-footer.config.yml
  nrrd-design-system/components/components/global-footer/global-footer.hbs
  nrrd-design-system/components/components/hero-ribbons/hero-ribbons.hbs
  nrrd-design-system/components/layouts/tables/tables.hbs
  nrrd-design-system/components/tables/advanced-table/advanced-table.config.yml
  nrrd-design-system/components/tables/advanced-table/advanced-table.hbs
  nrrd-design-system/components/tables/basic-table/basic-table.config.yml
  nrrd-design-system/components/tables/basic-table/basic-table.hbs
  package.json
  pages/about.html
Labels: workflow:testing

#2846 Adds guidance for open source contributors, adds subheadings
  CONTRIBUTING.md
Labels: workflow:testing

#2841 Normalizing icon styles and replacing font icons with SVGs
  _downloads/default.md
  _downloads/disbursements.md
  _downloads/federal-production.md
  _downloads/federal-revenue-by-company.md
  _downloads/federal-revenue-by-location.md
  _downloads/reconciliation.md
  _includes/data_and_docs.html
  _includes/how-it-works/footer.html
  _includes/layout/footer.html
  _includes/location/national-all-production.html
  _includes/location/national-disbursements.html
  _includes/location/national-federal-production.html
  _includes/location/national-gdp.html
  _includes/location/national-jobs.html
  _includes/location/national-revenue.html
  _includes/location/offshore-region-federal-production.html
  _includes/location/offshore-region-revenue.html
  _includes/location/opt-in/state-revenues.html
  _includes/location/revenue-type-table.html
  _includes/location/section-all-production.html
  _includes/location/section-disbursements.html
  _includes/location/section-exports.html
  _includes/location/section-federal-production.html
  _includes/location/section-gdp.html
  _includes/location/section-jobs.html
  _includes/location/section-revenue.html
  _includes/svg/chevron-lt.svg
  _includes/svg/icon-coal.svg
  _includes/svg/icon-data-docs.svg
  _includes/svg/icon-download.svg
  _includes/svg/icon-geothermal.svg
  _includes/svg/icon-hardrock.svg
  _includes/svg/icon-oil.svg
  _includes/svg/icon-renewables.svg
  _layouts/federal-revenue-by-company.html
  _layouts/reconciliation.html
  _sass/_fonts.scss
  _sass/_variables.scss
  _sass/blocks/_search.scss
  _sass/blocks/explore/_toggle.scss
  _sass/components/_accordions.scss
  _sass/components/_icons.scss
  _sass/components/_selectors.scss
  _sass/mixins/_selectors.scss
  img/icons/chevron-down-sm.svg
  img/icons/icon-min-white.svg
  img/icons/icon-min.svg
  img/icons/icon-plus-white.svg
  img/icons/icon-plus.svg
  img/icons/icon-search.svg
Labels: workflow:testing

#2909 Updates team members and contributors
  humans.txt
Labels: workflow:testing
