Repository ONRR/doi-extractives-data, pull requests merged in 2018-07, with the labels that each got.

#3024 Clears curated search terms from data file to expose only site pages
  _data/search.yml
Labels: workflow:testing

#3025 Replaces homepage world ranking text with vision-derived statement
  index.html
Labels: workflow:testing

#3030 Bump node on CI
  circle.yml
Labels: workflow:testing

#3015 2993 cy data fed prod
  _data/federal_county_production/AK.yml
  _data/federal_county_production/AL.yml
  _data/federal_county_production/AR.yml
  _data/federal_county_production/AZ.yml
  _data/federal_county_production/CA.yml
  _data/federal_county_production/CO.yml
  _data/federal_county_production/FL.yml
  _data/federal_county_production/ID.yml
  _data/federal_county_production/IL.yml
  _data/federal_county_production/KS.yml
  _data/federal_county_production/KY.yml
  _data/federal_county_production/LA.yml
  _data/federal_county_production/MI.yml
  _data/federal_county_production/MO.yml
  _data/federal_county_production/MS.yml
  _data/federal_county_production/MT.yml
  _data/federal_county_production/ND.yml
  _data/federal_county_production/NE.yml
  _data/federal_county_production/NM.yml
  _data/federal_county_production/NV.yml
  _data/federal_county_production/NY.yml
  _data/federal_county_production/OH.yml
  _data/federal_county_production/OK.yml
  _data/federal_county_production/PA.yml
  _data/federal_county_production/SC.yml
  _data/federal_county_production/SD.yml
  _data/federal_county_production/TX.yml
  _data/federal_county_production/UT.yml
  _data/federal_county_production/VA.yml
  _data/federal_county_production/WA.yml
  _data/federal_county_production/WV.yml
  _data/federal_county_production/WY.yml
  _data/national_federal_production.yml
  _data/offshore_federal_production_areas/Alaska.yml
  _data/offshore_federal_production_areas/Gulf.yml
  _data/offshore_federal_production_areas/Pacific.yml
  _data/offshore_federal_production_regions.yml
  _data/state_federal_production.yml
  _data/top_state_products/AR.yml
  _data/top_state_products/CA.yml
  _data/top_state_products/CO.yml
  _data/top_state_products/ID.yml
  _data/top_state_products/MO.yml
  _data/top_state_products/MT.yml
  _data/top_state_products/ND.yml
  _data/top_state_products/NM.yml
  _data/top_state_products/NV.yml
  _data/top_state_products/OK.yml
  _data/top_state_products/TX.yml
  _data/top_state_products/UT.yml
  _data/top_state_products/WY.yml
  _data/years.yml
  _downloads/default.md
  _downloads/federal-production.md
  data/federal-production/federal-production.tsv
  data/federal-production/federal-production.tsv.old
  downloads/federal_production_CY08-17.xlsx
Labels: enhancement:content, p1, workflow:testing

#3033 2993 cy data fed prod
  _data/federal_county_production/AK.yml
  _data/federal_county_production/AL.yml
  _data/federal_county_production/AR.yml
  _data/federal_county_production/AZ.yml
  _data/federal_county_production/CA.yml
  _data/federal_county_production/CO.yml
  _data/federal_county_production/FL.yml
  _data/federal_county_production/ID.yml
  _data/federal_county_production/IL.yml
  _data/federal_county_production/KS.yml
  _data/federal_county_production/KY.yml
  _data/federal_county_production/LA.yml
  _data/federal_county_production/MI.yml
  _data/federal_county_production/MO.yml
  _data/federal_county_production/MS.yml
  _data/federal_county_production/MT.yml
  _data/federal_county_production/ND.yml
  _data/federal_county_production/NE.yml
  _data/federal_county_production/NM.yml
  _data/federal_county_production/NV.yml
  _data/federal_county_production/NY.yml
  _data/federal_county_production/OH.yml
  _data/federal_county_production/OK.yml
  _data/federal_county_production/PA.yml
  _data/federal_county_production/SC.yml
  _data/federal_county_production/SD.yml
  _data/federal_county_production/TX.yml
  _data/federal_county_production/UT.yml
  _data/federal_county_production/VA.yml
  _data/federal_county_production/WA.yml
  _data/federal_county_production/WV.yml
  _data/federal_county_production/WY.yml
  _data/national_federal_production.yml
  _data/offshore_federal_production_areas/Alaska.yml
  _data/offshore_federal_production_areas/Gulf.yml
  _data/offshore_federal_production_areas/Pacific.yml
  _data/offshore_federal_production_regions.yml
  _data/state_federal_production.yml
  _data/top_state_products/AR.yml
  _data/top_state_products/CA.yml
  _data/top_state_products/CO.yml
  _data/top_state_products/ID.yml
  _data/top_state_products/MO.yml
  _data/top_state_products/MT.yml
  _data/top_state_products/ND.yml
  _data/top_state_products/NM.yml
  _data/top_state_products/NV.yml
  _data/top_state_products/OK.yml
  _data/top_state_products/TX.yml
  _data/top_state_products/UT.yml
  _data/top_state_products/WY.yml
  _data/years.yml
  _downloads/default.md
  _downloads/federal-production.md
  data/federal-production/federal-production.tsv
  data/federal-production/federal-production.tsv.old
  downloads/federal_production_CY08-17.xlsx
Labels: workflow:testing

#3034 2993 cy data fed prod
  _data/federal_county_production/AK.yml
  _data/federal_county_production/AL.yml
  _data/federal_county_production/AR.yml
  _data/federal_county_production/AZ.yml
  _data/federal_county_production/CA.yml
  _data/federal_county_production/CO.yml
  _data/federal_county_production/FL.yml
  _data/federal_county_production/ID.yml
  _data/federal_county_production/IL.yml
  _data/federal_county_production/KS.yml
  _data/federal_county_production/KY.yml
  _data/federal_county_production/LA.yml
  _data/federal_county_production/MI.yml
  _data/federal_county_production/MO.yml
  _data/federal_county_production/MS.yml
  _data/federal_county_production/MT.yml
  _data/federal_county_production/ND.yml
  _data/federal_county_production/NE.yml
  _data/federal_county_production/NM.yml
  _data/federal_county_production/NV.yml
  _data/federal_county_production/NY.yml
  _data/federal_county_production/OH.yml
  _data/federal_county_production/OK.yml
  _data/federal_county_production/PA.yml
  _data/federal_county_production/SC.yml
  _data/federal_county_production/SD.yml
  _data/federal_county_production/TX.yml
  _data/federal_county_production/UT.yml
  _data/federal_county_production/VA.yml
  _data/federal_county_production/WA.yml
  _data/federal_county_production/WV.yml
  _data/federal_county_production/WY.yml
  _data/national_federal_production.yml
  _data/offshore_federal_production_areas/Alaska.yml
  _data/offshore_federal_production_areas/Gulf.yml
  _data/offshore_federal_production_areas/Pacific.yml
  _data/offshore_federal_production_regions.yml
  _data/state_federal_production.yml
  _data/top_state_products/AR.yml
  _data/top_state_products/CA.yml
  _data/top_state_products/CO.yml
  _data/top_state_products/ID.yml
  _data/top_state_products/MO.yml
  _data/top_state_products/MT.yml
  _data/top_state_products/ND.yml
  _data/top_state_products/NM.yml
  _data/top_state_products/NV.yml
  _data/top_state_products/OK.yml
  _data/top_state_products/TX.yml
  _data/top_state_products/UT.yml
  _data/top_state_products/WY.yml
  _data/years.yml
  _downloads/default.md
  _downloads/federal-production.md
  data/federal-production/federal-production.tsv
  data/federal-production/federal-production.tsv.old
  downloads/federal_production_CY08-17.xlsx
Labels: workflow:testing

#3031 Use CircleCI 2.0
  .circleci/config.yml
  circle.yml
Labels: workflow:testing

#3032 Add styleguide-theme.css to override the theme
  css/styleguide-theme.scss
  css/styleguide.scss
  nrrd-design-system/fractal.js
  webpack.config.js
Labels: workflow:testing

#2999 updated packages
  package-lock.json
  package.json
Labels: bug:tech, workflow:testing

#3035 Update component documentation
  nrrd-design-system/components/_00-template/README.md
  nrrd-design-system/components/_preview.hbs
  nrrd-design-system/components/components/accordions/README.md
  nrrd-design-system/components/components/accordions/accordions--in-table.hbs
  nrrd-design-system/components/components/accordions/accordions--mobile-menu.hbs
  nrrd-design-system/components/components/accordions/accordions--mobile.hbs
  nrrd-design-system/components/components/accordions/accordions.config.yml
  nrrd-design-system/components/components/accordions/accordions.hbs
  nrrd-design-system/components/components/breadcrumbs/README.md
  nrrd-design-system/components/components/breadcrumbs/breadcrumbs.config.yml
  nrrd-design-system/components/components/breadcrumbs/breadcrumbs.hbs
  nrrd-design-system/components/components/buttons/README.md
  nrrd-design-system/components/components/buttons/buttons.hbs
  nrrd-design-system/components/components/cards/README.md
  nrrd-design-system/components/components/cards/cards.config.yml
  nrrd-design-system/components/components/cards/cards.hbs
  nrrd-design-system/components/components/charts/README.md
  nrrd-design-system/components/components/charts/charts.config.yml
  nrrd-design-system/components/components/charts/charts.hbs
  nrrd-design-system/docs/02-how-to.md
  nrrd-design-system/fractal.js
Labels: workflow:testing

#2926 Remove javascript from tab component in style guide
  nrrd-design-system/components/components/tabs/README.md
  nrrd-design-system/components/components/tabs/tabs.hbs
Labels: workflow:testing

#3053 Adds section on BSEE proposed rule, lowers reading grade level
  _how-it-works/laws-and-regulations/federal-reforms.md
Labels: workflow:testing

#3063 Round one of tag updates; redirect and year updates
  _data/years.yml
  _how-it-works/federal-revenue-by-company/index.html
  _how-it-works/nonenergy-minerals.md
  _how-it-works/the-process/minerals.html
  _how-it-works/tribal-production.md
  _states/MT.md
Labels: workflow:testing

#3059 Adds metadata to state pages for search
  _plugins/search.rb
  _states/AK.md
  _states/AL.md
  _states/AR.md
  _states/AZ.md
  _states/CA.md
  _states/CO.md
  _states/CT.md
  _states/DC.md
  _states/DE.md
  _states/FL.md
  _states/GA.md
  _states/HI.md
  _states/IA.md
  _states/ID.md
  _states/IL.md
  _states/IN.md
  _states/KS.md
  _states/KY.md
  _states/LA.md
  _states/MA.md
  _states/MD.md
  _states/ME.md
  _states/MI.md
  _states/MN.md
  _states/MO.md
  _states/MS.md
  _states/MT.md
  _states/NC.md
  _states/ND.md
  _states/NE.md
  _states/NH.md
  _states/NJ.md
  _states/NM.md
  _states/NV.md
  _states/NY.md
  _states/OH.md
  _states/OK.md
  _states/OR.md
  _states/PA.md
  _states/RI.md
  _states/SC.md
  _states/SD.md
  _states/TN.md
  _states/TX.md
  _states/UT.md
  _states/VA.md
  _states/VT.md
  _states/WA.md
  _states/WI.md
  _states/WV.md
  _states/WY.md
Labels: workflow:testing

#3057 Edits search intro copy and tweaks layout
  _sass/blocks/_search.scss
  pages/search-results.html
Labels: workflow:testing

#3021 Mobile font icon replacement with SVGs
  _includes/layout/mobile-nav.html
  _includes/svg/chevron-dn.svg
  _includes/svg/chevron-up.svg
  _sass/components/_drawer.scss
  img/icons/icon-close-x.svg
  img/icons/icon-menu.svg
  js/components/eiti-toggle.js
Labels: workflow:testing

#3065 Updates static chart for AML fund, associated alt text
  _how-it-works/aml-fees.md
  img/AML_unapprop-growth.svg
Labels: workflow:testing

#3079 Updates (another) redirect for company data, adds waters to description
  _explore/revenue/federal-revenue-by-company/index.html
  _layouts/federal-revenue-by-company.html
Labels: workflow:testing

#3081 Adds waters to second instance of descriptive text
  _layouts/federal-revenue-by-company.html
Labels: workflow:testing

#3066 Removes content that doesn't align with product vision
  _how-it-works/corporate-income-tax.md
  _how-it-works/default.md
  _how-it-works/forestry.md
  _how-it-works/lease-process-offshore.md
  _how-it-works/lease-process-onshore.md
Labels: workflow:testing

#3049 [WIP] AML updates and edits
  _how-it-works/aml-fees.md
  _how-it-works/tribal-ownership-and-governance.md
  img/AML-unapprop-alloc.svg
  img/AML_state-grants.svg
Labels: workflow:testing

#3082 Add map examples to styleguide
  _config-dev.yml
  _config.yml
  _includes/county-map.html
  _includes/icon-map.html
  _includes/location/section-ownership.html
  _includes/maps/federal_land_ownership.svg
  _includes/offshore-area-map.html
  _includes/state-map.html
  _layouts/state-page.html
  css/styleguide.scss
  maps/README.md
  nrrd-design-system/components/_preview.hbs
  nrrd-design-system/components/_side-navigation-preview.hbs
  nrrd-design-system/components/components/maps/case-study/README.md
  nrrd-design-system/components/components/maps/case-study/case-study.hbs
  nrrd-design-system/components/components/maps/county-production/README.md
  nrrd-design-system/components/components/maps/county-production/county-production.config.yml
  nrrd-design-system/components/components/maps/county-production/county-production.hbs
  nrrd-design-system/components/components/maps/land-ownership/README.md
  nrrd-design-system/components/components/maps/land-ownership/land-ownership--national.hbs
  nrrd-design-system/components/components/maps/land-ownership/land-ownership.config.yml
  nrrd-design-system/components/components/maps/land-ownership/land-ownership.hbs
  nrrd-design-system/components/components/maps/maps.config.yml
  nrrd-design-system/components/components/maps/maps.hbs
  nrrd-design-system/components/components/text-filter/text-filter.hbs
  nrrd-design-system/components/styles/colors/primary-palette/primary-palette.hbs
  nrrd-design-system/components/styles/colors/supporting-palette/supporting-palette.hbs
  nrrd-design-system/components/styles/icons/icons.hbs
  webpack.config.js
Labels: workflow:testing
